services:
  s3:
    container_name: s3
    image: localstack/localstack:latest
    ports:
      - ${GATEWAY_LISTEN}:${GATEWAY_LISTEN}
    volumes:
      - localstack-data:/var/lib/localstack
    env_file:
      - .env

  redis:
    image: redis:8.0-M02-bookworm
    container_name: redis
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 15s
      timeout: 15s
      retries: 4
    depends_on:
      redis:
        condition: service_healthy

#  backend:
#    container_name: backend
#    env_file:
#      - .env
#    ports:
#      - ${APP_PORT}:${APP_PORT}
#    command: bash -c "alembic upgrade head && uvicorn src.main:app --host ${APP_HOST} --port ${APP_PORT}"
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      mysql:
#        condition: service_healthy

#  celery_worker:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: celery_worker
#    command: celery -A src.auth.service:celery worker --loglevel=info
#    depends_on:
#      trainme:
#         condition: service_healthy
#    healthcheck:
#      test: [ "CMD", "celery", "-A", "src.auth.service:celery", "status" ]
#      interval: 10s
#      timeout: 10s
#      retries: 3

volumes:
  localstack-data:
