"""feat: add property

Revision ID: 07420f27f8ff
Revises: ba5cfddc6d19
Create Date: 2025-04-24 00:07:02.614464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07420f27f8ff'
down_revision: Union[str, None] = 'ba5cfddc6d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads_report', sa.Column('path_to_llm_response', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ads_report', 'path_to_llm_response')
    # ### end Alembic commands ###
