"""feat: add ads model

Revision ID: 4a6ace215cb2
Revises: 871d22456d47
Create Date: 2025-04-01 06:00:22.148369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6ace215cb2'
down_revision: Union[str, None] = '871d22456d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads_report', sa.Column('path_to_clustered_df', sa.String(length=255), nullable=True))
    op.add_column('ads_report', sa.Column('path_to_impact_df', sa.String(length=255), nullable=True))
    op.drop_column('ads_report', 'path_to_df')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads_report', sa.Column('path_to_df', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('ads_report', 'path_to_impact_df')
    op.drop_column('ads_report', 'path_to_clustered_df')
    # ### end Alembic commands ###
