"""feat: add ads model

Revision ID: ba5cfddc6d19
Revises: 
Create Date: 2025-04-03 04:25:41.966457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5cfddc6d19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('info', sa.String(length=255), nullable=True),
    sa.Column('bad_segments', sa.String(length=255), nullable=True),
    sa.Column('path_to_clustered_df', sa.String(length=255), nullable=True),
    sa.Column('path_to_impact_df', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ads_report')
    # ### end Alembic commands ###
