"""add is_superuser field

Revision ID: 0d7a60d160aa
Revises: 4e12b66abb3e
Create Date: 2024-11-03 01:45:42.705890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7a60d160aa'
down_revision: Union[str, None] = '4e12b66abb3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth', 'is_superuser')
    # ### end Alembic commands ###
