token = "y0__xD-15LEBhiOgjYgu53kyhLbssECE76XIqKImMH2ph83nit1Cw"
client_id="7dfabf24dbae4514868db23a991fb92e"

[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "ads_company_secret"
client_id = "7dfabf24dbae4514868db23a991fb92e"
client_secret = "75dea7eefcb841839b3f37c3a41c65ad"
response_type="code"
server_metadata_url = "https://oauth.yandex.ru/authorize?response_type=code"
