"""feat: add ads model

Revision ID: 0312437b0c17
Revises: 38f1fd043bfc
Create Date: 2025-03-17 20:42:26.597543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0312437b0c17'
down_revision: Union[str, None] = '38f1fd043bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asd_info', sa.Column('bad_company_segments', sa.String(length=255), nullable=False))
    op.add_column('asd_info', sa.Column('cluster_image_link', sa.String(length=255), nullable=False))
    op.drop_column('asd_info', 'bad_company_segment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asd_info', sa.Column('bad_company_segment', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('asd_info', 'cluster_image_link')
    op.drop_column('asd_info', 'bad_company_segments')
    # ### end Alembic commands ###
