"""feat: add ads model

Revision ID: 38f1fd043bfc
Revises: cc9e05745880
Create Date: 2025-03-17 20:07:46.402042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38f1fd043bfc'
down_revision: Union[str, None] = 'cc9e05745880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asd_info', sa.Column('uploaded_at', sa.DateTime(), nullable=False))
    op.add_column('asd_info', sa.Column('is_ready', sa.Boolean(), nullable=False))
    op.add_column('asd_info', sa.Column('optimal_clusters', sa.Integer(), nullable=False))
    op.add_column('asd_info', sa.Column('bad_company_segment', sa.String(length=255), nullable=False))
    op.drop_constraint('asd_info_owner_id_fkey', 'asd_info', type_='foreignkey')
    op.drop_column('asd_info', 'owner_id')
    op.drop_column('asd_info', 'report_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asd_info', sa.Column('report_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('asd_info', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('asd_info_owner_id_fkey', 'asd_info', 'user', ['owner_id'], ['id'])
    op.drop_column('asd_info', 'bad_company_segment')
    op.drop_column('asd_info', 'optimal_clusters')
    op.drop_column('asd_info', 'is_ready')
    op.drop_column('asd_info', 'uploaded_at')
    # ### end Alembic commands ###
